### ISSUE TITLE
Startup error, unable to open

### ISSUE THREAD

**Issue by dayi23** [PalworldModding/Docs#13]
I have browsed through Palworld Modding Documents step by step

Create it with a document, but I don't know where the problem lies and I can't open it either
![3ea9f5f7d631ba78e4c83a8f1aec32d](https://github.com/PalworldModding/Docs/assets/160402505/2c368f5b-982e-4103-9690-dede9d590320)
![e5f9b91f84943f254caa4a71baa4ec5](https://github.com/PalworldModding/Docs/assets/160402505/ac11b331-ce9f-4db9-9577-381deeaccf14)

**Comment by Okaetsu** [comment]
Hi, I'm not sure if you're still around, but if you are, open an issue over at https://github.com/localcc/PalworldModdingKit/issues as this is more meant for the Modding Docs, thanks!
